### ISSUE TITLE
All routes are returning 404

### ISSUE THREAD

**Issue by pnunn** [mdfaizan7/go-authentication-boilerplate#2]
Hi Fiazan,

I'm still hacking away at your wonderful tutorial, now have it all compiling and running, but for some reason all of the routes are returning 404 (even the default /).

I've checked my code against your repo and it seems to be consistent.

Some simple debugging shows that the SetupUserRoutes function is being called. 

Is there a way to determine what routes are being configured with fibers?

Just for reference, I'm testing with postman  as GET localhost:3000/signup which I think is correct.

**Comment by mdfaizan7** [comment]
If you see the `SetupRoutes` function in the `router` package, you will see that all the api routes fall under the `/api` group. Try the `localhost:3000/api/signup` and that should work.

**Comment by pnunn** [comment]
Thank you Fiazan,

please excuse my ignorance... works as expected. 👍
